name: Release

on:
  release:
    types:
      - published

env:
  PROJECT: capstone
  IMAGE_VERSION: ${{ github.sha }}
  DOCKER_ACCOUNT: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: $DOCKER_ACCOUNT
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: rikuvan/capstone:latest
          build-args:
      - name: Build Docker image
        env:
          AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
          AWS_CREDENTIALS: ${{ secrets.AWS_CREDENTIALS }}
          BASIC_AUTH_CREDENTIALS: ${{ secrets.BASIC_AUTH_CREDENTIALS }}
          HTTP_PORT: ${{ secrets.HTTP_PORT }}
        run: |
          docker build \
            --build-arg AWS_BUCKET=$ \
            --build-arg AWS_CREDENTIALS=$AWS_CREDENTIALS \
            --build-arg BASIC_AUTH_CREDENTIALS=$BASIC_AUTH_CREDENTIALS \
            --build-arg HTTP_PORT=$HTTP_PORT \
            -t $DOCKER_ACCOUNT/$PROJECT:$IMAGE_VERSION \
            -t $DOCKER_ACCOUNT/$PROJECT:latest .
      - name: Push Docker image
        run: |
          docker push $DOCKER_ACCOUNT/$PROJECT:$IMAGE_VERSION
          docker push $DOCKER_ACCOUNT/$PROJECT:latest
